"""RP2040/RP2350 PIO-backed IR :class:`PulseWriter` adapter.

This is the hardware *leaf* for non-blocking IR transmit. :class:`PioPulseWriter`
drives an ``rp2pio.StateMachine`` with a DMA-fed background write so
``write_pulses`` *starts* the pulse train and returns immediately, leaving the
carrier to clock out in hardware while the main loop keeps running. The 38 kHz
carrier is generated by the PIO program itself, so the writer feeds the state
machine mark/space durations only.

The module is import-guarded: ``rp2pio`` and ``adafruit_pioasm`` exist only on
RP2040/RP2350 silicon, so they are imported lazily inside :func:`make_state_machine`
rather than at module load. Importing this module on a non-RP board (or under
CPython) is safe; only building a state machine touches the hardware libraries.

All protocol logic lives in :mod:`hardware.shared.ir_protocol` and
:mod:`hardware.shared.ir_transport`; this leaf owns only the DMA handoff, the
µs→carrier-period conversion, the in-flight buffer reference, and the busy/idle
signal.

Timing model
------------
The encoder emits durations in **microseconds** (the same array the blocking
``pulseio.PulseOut`` path consumes, where the hardware PWM gates the carrier by
µs). The PIO program here instead counts **carrier periods**: the state machine
runs at 1 MHz (1 clock = 1 µs) and every mark/space loop iteration is exactly
26 clocks = 26 µs = one ~38.46 kHz carrier period. So a duration of *D* µs is
transmitted as ``round(D / 26)`` loop iterations. :func:`_duration_us_to_loops`
does that conversion in :meth:`PioPulseWriter.write_pulses`, in place, before the
DMA starts — the step that was missing when µs values were fed straight in as
raw loop counts.

.. note::
   The PIO program's on-wire timing is **not** exercised by CPython tests (the
   stubbed ``rp2pio`` runs no PIO), so it is pending on-hardware validation
   under the transmit spike (#551). The µs→loops conversion *is* unit-tested.
"""

from __future__ import annotations

try:
    from typing import Final
except ImportError:
    pass

from array import array

from hardware.shared.ir_transport import PulseWriter

# State-machine clock: 1 MHz so one PIO clock is exactly 1 µs. This is what lets
# the [delay] counts in the program below be read directly as microseconds.
_SM_HZ: Final = 1_000_000

# Microseconds per mark/space loop iteration. Each iteration is 26 PIO clocks
# (see _PIO_SOURCE), so at _SM_HZ it spans 26 µs and emits one ~38.46 kHz carrier
# period. Every duration is quantised to a whole number of these periods.
_CARRIER_PERIOD_US: Final = 26

# Trailing silence appended to every frame. Serves two purposes: (1) it pads the
# frame to an even number of durations, which keeps the PIO program's strict
# pull-mark / pull-space phase aligned across back-to-back frames (an odd-length
# frame would clock the *next* frame's header mark out as a space, inverting it —
# see write_pulses); (2) it is real inter-frame silence for the receiver to
# delimit on. Tunable: larger is safer for delimiting, smaller costs less rate.
_INTERFRAME_GAP_US: Final = 5000

# One 38.46 kHz carrier period, expressed as PIO instruction delays. A mark
# iteration drives the pin high for 13 µs then low for 13 µs; a space iteration
# holds the pin low for the full 26 µs. Durations arrive as loop counts (see
# _duration_us_to_loops) — 16-bit array('H') elements, so each `out` pulls only
# the 16 bits a count occupies (writes narrower than 32 bits are duplicated into
# the other half of the FIFO word by the RP2040 bus; pulling 32 would read the
# duplicated word instead of the count).
_PIO_SOURCE: Final = """
.program ir_carrier
    pull block
    out x, 16
mark_loop:
    set pins, 1 [12]
    set pins, 0 [11]
    jmp x-- mark_loop
    pull block
    out y, 16
space_loop:
    set pins, 0 [24]
    jmp y-- space_loop
"""


def _duration_us_to_loops(duration_us: int) -> int:
    """Convert a mark/space duration in µs to a PIO loop count.

    Each loop iteration spans :data:`_CARRIER_PERIOD_US` µs, so the duration is
    rounded to the nearest whole number of periods. One is then subtracted
    because the program's ``jmp x-- `` runs the loop body ``count + 1`` times
    (the scratch register is tested before the post-decrement), so a stored
    ``n`` yields ``n + 1`` iterations.

    Args:
        duration_us: Mark or space duration in microseconds (always ≥ the
            protocol's base unit, so the result is never negative).

    Returns:
        The value to feed the state machine: one less than the number of 26 µs
        carrier periods the duration rounds to (minimum 0, i.e. one iteration).
    """
    periods = (duration_us + _CARRIER_PERIOD_US // 2) // _CARRIER_PERIOD_US
    if periods < 1:
        periods = 1
    return periods - 1


def make_state_machine(pin: object) -> object:
    """Build one ``rp2pio.StateMachine`` driving the carrier program on *pin*.

    The ``rp2pio`` / ``adafruit_pioasm`` imports happen here, not at module
    load, so this module imports cleanly on boards without PIO. The runtime
    auto-allocates the PIO block and state machine — block placement is not a
    code branch.

    Args:
        pin: The transmit pin (e.g. a ``board`` pin) the emitter is wired to.

    Returns:
        A configured ``rp2pio.StateMachine`` ready to be wrapped in a
        :class:`PioPulseWriter`.
    """
    import adafruit_pioasm
    import rp2pio

    program = adafruit_pioasm.Program(_PIO_SOURCE)
    # rp2pio.StateMachine takes the assembled program and frequency as
    # positional-only args (they precede the keyword-only `*`); the transmit pin
    # is the program's `set pins` target, wired via first_set_pin. The clock is
    # 1 MHz so the program's per-instruction delays count in microseconds.
    return rp2pio.StateMachine(
        program.assembled,
        _SM_HZ,
        first_set_pin=pin,
    )


class PioPulseWriter(PulseWriter):
    """Non-blocking IR :class:`PulseWriter` over an ``rp2pio.StateMachine``.

    ``write_pulses`` converts the µs durations to carrier-period loop counts,
    hands the array to the state machine's ``background_write`` (DMA-fed), and
    returns immediately — the carrier clocks out in hardware while the CPU
    continues. The writer owns the in-flight pulse buffer for the full DMA
    lifetime, keeping it referenced until ``is_busy()`` next reports ``False``
    (a buffer freed mid-DMA would corrupt the transfer).

    Args:
        state_machine: An ``rp2pio.StateMachine`` already configured with the
            carrier program (see :func:`make_state_machine`).
    """

    __slots__ = ("_inflight", "_sm")

    def __init__(self, state_machine: object) -> None:
        self._sm = state_machine
        # The pulse array handed to the DMA; held until the write completes so
        # the buffer cannot be garbage-collected out from under the transfer.
        self._inflight: object | None = None

    def write_pulses(self, durations: array[int] | list[int]) -> None:
        """Start a non-blocking DMA write of *durations* and return immediately.

        Builds the DMA buffer by converting each µs duration to a carrier-period
        loop count (see :func:`_duration_us_to_loops`) and appending a trailing
        gap so the buffer holds an **even** number of durations. The even count
        is required for correctness, not just spacing: the PIO program pulls
        strictly mark, space, mark, space, … and keeps that phase across the
        wrap between frames, so an odd-length frame would clock the next frame's
        header mark out as a space — inverting every following frame. The
        appended :data:`_INTERFRAME_GAP_US` space both restores even parity and
        gives the receiver silence to delimit on.

        The built buffer is kept referenced until the transfer completes —
        freeing it mid-DMA would corrupt the transfer.

        Args:
            durations: An ``array('H', …)`` of mark/space durations (µs),
                alternating mark/space, starting with a mark. Odd-length (the
                Aura encoder ends on a lead-out mark). The PIO program adds the
                38 kHz carrier.
        """
        n = len(durations)
        # Pad odd frames to even with one trailing gap space (keeps mark/space
        # phase aligned across frames; see the docstring). The Aura encoder is
        # always odd, so this appends exactly once in practice.
        pad = n % 2
        buffer = array("H", bytearray((n + pad) * 2))
        for i in range(n):
            buffer[i] = _duration_us_to_loops(durations[i])
        if pad:
            buffer[n] = _duration_us_to_loops(_INTERFRAME_GAP_US)
        self._inflight = buffer
        self._sm.background_write(buffer)

    def is_busy(self) -> bool:
        """Return ``True`` while a DMA write this writer started is still outstanding.

        Gated on the in-flight buffer reference, *then* the state machine's
        ``writing`` flag. The gate matters: ``rp2pio`` never initialises the
        ``dma_completed`` field its ``writing`` property negates until the first
        ``background_write``, so a freshly constructed state machine can report
        ``writing == True`` from uninitialised memory. Trusting it directly
        would deadlock — the caller's "only send when idle" guard would never
        fire, so no write would ever start to clear the flag. Only a write this
        writer actually kicked off (``_inflight`` set) can be outstanding.

        On the falling edge (the first call that observes ``writing`` is
        ``False`` while a buffer is in flight) it releases the buffer so it can
        be reclaimed.

        Returns:
            ``True`` while a background write is in flight, else ``False``.
        """
        if self._inflight is None:
            return False
        if self._sm.writing:
            return True
        # Falling edge: the DMA is done, drop the buffer reference.
        self._inflight = None
        return False
