"""RP2040/RP2350 PIO-backed IR :class:`PulseWriter` adapter.

This is the hardware *leaf* for non-blocking IR transmit. :class:`PioPulseWriter`
drives an ``rp2pio.StateMachine`` with a DMA-fed background write so
``write_pulses`` *starts* the pulse train and returns immediately, leaving the
carrier to clock out in hardware while the main loop keeps running. The 38 kHz
carrier is generated by the PIO program itself, so the writer feeds the state
machine raw mark/space durations only.

The module is import-guarded: ``rp2pio`` and ``adafruit_pioasm`` exist only on
RP2040/RP2350 silicon, so they are imported lazily inside :func:`make_state_machine`
rather than at module load. Importing this module on a non-RP board (or under
CPython) is safe; only building a state machine touches the hardware libraries.

All protocol logic lives in :mod:`hardware.shared.ir_protocol` and
:mod:`hardware.shared.ir_transport`; this leaf owns only the DMA handoff, the
in-flight buffer reference, and the busy/idle signal.
"""

from __future__ import annotations

try:
    from typing import Final
except ImportError:
    pass

from array import array

from hardware.shared.ir_transport import PulseWriter

# 38 kHz IR carrier, synthesised inside the PIO program rather than by hardware
# PWM, so the writer feeds raw mark/space durations only.
_CARRIER_HZ: Final = 38_000

# Carrier-gating scheme: the program pulls a mark duration, emits that many
# 38 kHz carrier cycles, then pulls a space duration and holds the pin low for
# it — so the carrier lives in the PIO program, not in a pre-expanded buffer.
# The assembly is validated on real hardware by the sibling spike issue (#459).
_PIO_SOURCE: Final = """
.program ir_carrier
; One 38 kHz carrier cycle per loop iteration; the duration word from the FIFO
; gates how many carrier cycles a mark lasts. A space holds the pin low for the
; same count. Mark/space alternation starts with a mark.
    pull block
    out x, 32
mark_loop:
    set pins, 1 [1]
    set pins, 0
    jmp x-- mark_loop
    pull block
    out x, 32
space_loop:
    set pins, 0
    jmp x-- space_loop
"""


def make_state_machine(pin: object) -> object:
    """Build one ``rp2pio.StateMachine`` driving the carrier program on *pin*.

    The ``rp2pio`` / ``adafruit_pioasm`` imports happen here, not at module
    load, so this module imports cleanly on boards without PIO. The runtime
    auto-allocates the PIO block and state machine — block placement is not a
    code branch.

    Args:
        pin: The transmit pin (e.g. a ``board`` pin) the emitter is wired to.

    Returns:
        A configured ``rp2pio.StateMachine`` ready to be wrapped in a
        :class:`PioPulseWriter`.
    """
    import adafruit_pioasm
    import rp2pio

    program = adafruit_pioasm.Program(_PIO_SOURCE)
    # rp2pio.StateMachine takes the assembled program and frequency as
    # positional-only args (they precede the keyword-only `*`); the transmit pin
    # is the program's `set pins` target, wired via first_set_pin. Two PIO clocks
    # per carrier cycle (one high, one low half-period).
    return rp2pio.StateMachine(
        program.assembled,
        _CARRIER_HZ * 2,
        first_set_pin=pin,
    )


class PioPulseWriter(PulseWriter):
    """Non-blocking IR :class:`PulseWriter` over an ``rp2pio.StateMachine``.

    ``write_pulses`` hands the pulse array to the state machine's
    ``background_write`` (DMA-fed) and returns immediately — the carrier clocks
    out in hardware while the CPU continues. The writer owns the in-flight pulse
    buffer for the full DMA lifetime, keeping it referenced until ``is_busy()``
    next reports ``False`` (a buffer freed mid-DMA would corrupt the transfer).

    Args:
        state_machine: An ``rp2pio.StateMachine`` already configured with the
            carrier program (see :func:`make_state_machine`).
    """

    __slots__ = ("_inflight", "_sm")

    def __init__(self, state_machine: object) -> None:
        self._sm = state_machine
        # The pulse array handed to the DMA; held until the write completes so
        # the buffer cannot be garbage-collected out from under the transfer.
        self._inflight: object | None = None

    def write_pulses(self, durations: array[int] | list[int]) -> None:
        """Start a non-blocking DMA write of *durations* and return immediately.

        The writer keeps a reference to *durations* until the transfer
        completes — freeing the buffer mid-DMA would corrupt the transfer.

        Args:
            durations: An ``array('H', …)`` of pulse durations (µs), alternating
                mark/space, starting with a mark. The PIO program adds the
                38 kHz carrier.
        """
        self._inflight = durations
        self._sm.background_write(durations)

    def is_busy(self) -> bool:
        """Return ``True`` while the DMA write is still outstanding.

        Reads the state machine's ``writing`` flag. On the falling edge (the
        first call that observes ``writing`` is ``False``) it releases the
        in-flight buffer so it can be reclaimed.

        Returns:
            ``True`` while a background write is in flight, else ``False``.
        """
        if self._sm.writing:
            return True
        # Falling edge: the DMA is done, drop the buffer reference.
        self._inflight = None
        return False
